### ISSUE TITLE
Couldn't find edge_list_short.txt

### ISSUE THREAD

**Issue by okpatil4u** [dbgannon/graphs#1]
Hello,

Found this repo from your well written article at https://cloud4scieng.org/2020/08/28/deep-learning-on-graphs-a-tutorial/. Good work. I couldn't find the edge_list_short.txt file. Could you please upload it so that we can follow the tutorial properly ?

Kudos !

**Comment by dbgannon** [comment]
Will do today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dbgannon** [comment]
Done.  In repo now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by okpatil4u** [comment]
Thank you !
